### ISSUE TITLE
Atelier Palette crashes my patches

### ISSUE THREAD

**Issue by Kleinemaschinen** [Xenakios/Atelier#16] opened 2021-10-31 13:42 UTC
Hello there, 
Atelier Palette crashes my patches, this only started this weekend. See following log from Jens.Pieter.Nielsen and my topic on Rack forum
https://community.vcvrack.com/t/2-palettes-and-arps-keeping-crashing/14570/4

add:

[50.229 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
3: ZN4rack10appDestroyEv 0x456435
2: raise 0x246cd9c0
1: abort 0x246d20b0
0: ZN6plaits11StringVoice6RenderEbbfffffPfS1_S1_y 0x3e2b746
seems it’s the palette/plaits module ? The log is not written to every time it crashes.

Thanks hope this helps to solve the problem, I love using Palettes in VCV.

**Comment by Xenakios** [comment] 2021-10-31 15:45
Looks like this is going to be difficult to debug.

**Comment by Xenakios** [comment] 2021-11-22 15:00
Closing, because it was not in the end clear if the problem was in Palette or in other modules used in the patch that was crashing. However, during trying to find the cause of the issue, it was discovered Palette did not handle incoming abnormal floating point numbers gracefully, and that was fixed for V1 by filtering those from the CV inputs. Rack V2 fixes this internally globally for all modules.

**Closed as completed by Xenakios** 2021-11-22 15:00 UTC
