### ISSUE TITLE
Visual lag when adding Palette to the patch

### ISSUE THREAD

**Issue by vcvrackideas** [Xenakios/Atelier#10] opened 2020-07-22 09:39 UTC
Hi! So visually rack has some lag when I add Palette to the patch. It's pretty noticeable when monitor is in 75hz, and with Palette especially with 2 or more instance it works as when in 20hz mode or something like that, so the speed of overall graphics is reduced. It's always ok when remove Palette from the patch...but I don't want to do that because I love your module) 
So what do you think is it possible to reduce that lag? If it's hard to reproduced on your machine (btw I'm on windows) just tell me what do to to reproduce it on my side. I think it's due some svgs because it's only module in the rack where there is no blur at the center of the module while zooming.

**Comment by Xenakios** [comment] 2020-07-22 12:41
Testing here by setting Rack to 60 frames per second I seem to be getting just the increased frame rate in Rack as expected, with increased CPU load of course. (Desktop machine, Windows 7, Intel i7 CPU from 2014 and NVidia GeForce GTX 750 Ti GPU from about the same time period.)

I can recheck that I am not doing something stupid like reloading the SVGs repeatedly in the code when not necessary, but I am quite sure that is not the case. It could be possible the SVGs from Pyer are harder to render than SVGs usually. I can reproduce the phenomenon that the Palette panel is not blurred when zooming in while the other modules do that.

**Comment by vcvrackideas** [comment] 2020-07-22 12:47
ok, my laptop is pretty much the same as yours and PC is xeon (hasswell) and AMD rx470, so quite powerful. I think it would be best that I will shoot some test video at 60fps with OBS with XY scrolling in the Rack without Palette and with to be sure for right understanding from you because my English can't explain in details the issue. Hope to do that today or tomorrow. XY scrolling reacts pretty fast while in 75hz (or fps) on some kind of visual lags in VCV Rack (or CPU lags, doesn't know about it yet). BTW disabling or enabling low cpu just decrease DSP cycles but graphics is staying still the same.

**Comment by Xenakios** [comment] 2020-07-22 13:00
Hmm. Now I actually do get the blurring "effect" in the Palette panel after all when zooming around in the GUI...

I need to confirm from Andrew how the plain SvgWidget actually works. It looks like the Knobs etc that also use SVG files do some caching into bitmaps so they don't need to render the whole SVG from scratch each time. The plain SvgWidget (which is used for the dynamically changing panels in Palette) might not have anything like that implemented by default.

**Comment by Xenakios** [comment] 2020-07-26 20:06
I did the best I could so far, so closing this for now.

**Closed as completed** 2020-07-26 20:06 UTC
